//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooksApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_books
    {
        public string book_id { get; set; }
        public string book_name { get; set; }
        public Nullable<System.DateTime> buyDate { get; set; }
        public string link { get; set; }
    }
}
